version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: m3trajetta/udagram-reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: m3trajetta/udagram-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: m3trajetta/udagram-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: m3trajetta/udagram-frontend
